### ISSUE TITLE
What is the format of checkM output needed?

### ISSUE THREAD

**Issue by stefcamp** [MrOlm/drep#52]
I have problems in running checkM due to issues with python2/python3. I would like to provide as input the output file of checkM in order to skip the use of python2. I tried using the command with 
dRep dereplicate working_dir  -g directory_with_genomes/*.fa --genomeInfo checkMfile

As checkM output I used "bin_stats_ext.tsv" but again dRep terminates with an error and I cannot understand what is the format of the input file.
Could you please provide an example?
Thanks
--
Stefano

**Comment by MrOlm** [comment]
Hi Stefano,

See here for an example file: https://drep.readthedocs.io/en/master/advanced_use.html#using-external-genome-quality-information

You basically just need 3 columns- genome, completeness, and contamination, separated with commas

**Comment by jennifer-allott** [comment]
I believe the file that I am proving follows this format (top few lines below): 

genome,completeness,contamination
Bin_1-contigs.fa,84.48,70.69
Bin_10-contigs.fa,75.61,11.08
Bin_11-contigs.fa,61.68,16.38
Bin_12-contigs.fa,99.25,0
Bin_12_A-contigs.fa,84.68,20.6

However I have still receiving error messages that genome, completeness etc. is missing from the input file. Any suggestions or something that I am missing?

`(venv) caelia:venv kathy$ bin/drep dereplicate /Volumes/Backup_Drive/assembly/results_2 -g /Volumes/Backup_Drive/assembly/test_combined/*.fa --genomeInfo /Volumes/Backup_Drive/assembly/sample_checkm.csv 

***************************************************

    ..:: dRep dereplicate Step 1. Filter ::..

***************************************************
Will filter the genome list
Calculating genome info of genomes
77.27% of genomes passed length filtering
Traceback (most recent call last):
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 114, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 161, in _validate_genomeInfo
    assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: genome missing from GenomeInfo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/drep", line 33, in <module>
    controller.parseArguments(args)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/controller.py", line 86, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 81, in d_filter_wrapper
    Gdb = _get_run_genomeInfo(wd, bdb, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 118, in _get_run_genomeInfo
    Tdb = _validate_genomeInfo(Idb, bdb)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 161, in _validate_genomeInfo
    assert r in Idb.columns, "{0} missing from GenomeInfo".format(r)
AssertionError: completeness missing from GenomeInfo`

**Comment by MrOlm** [comment]
Hello,

To help diagnose it I pushed some changes to dRep in a special branch so we can get a better idea of what is going wrong. It just gives some more log information.

This special branch is called "BarbBranch"

To install it try the following steps:

1) Download the newest version of dRep using the command "git clone git@github.com:MrOlm/drep.git"

2) Change directories into the dRep folder 

3) Switch to the special branch using the command "git checkout BarbBranch"

4) Install this special branch using the command "pip install . --upgrade" 

You'll know it's working when the version number for dRep is 2.3.2B. You can see then version number on the help screen ("dRep -h")

Once you have the special branch working, go ahead and give it a shot again. It should print out what it thinks the columns are in the input that you gave it, and what it thinks genomeInfo looks like.

Sorry for the difficulty- this seems like a pretty strange bug.

Best,
Matt

**Comment by jennifer-allott** [comment]
I think I've now ran into an error regarding multiple versions of dRep, but I'm not sure. Any help would be much appreciated so I can get around this roadblock. 

$ dRep dereplicate_wf /Volumes/Backup_Drive/assembly/results_3 -g /Volumes/Backup_Drive/assembly/test_combined/*.fa --Chdb /Volumes/Backup_Drive/assembly/sample_checkm.txt
***************************************************
    ..:: dRep Step 1. Filter ::..
***************************************************
    
Will filter the genome list
Calculating genome info of genomes
77.27% of genomes passed length filtering
Running prodigal
Traceback (most recent call last):
  File "./dRep", line 33, in <module>
    controller.parseArguments(args)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/controller.py", line 144, in parseArguments
    self.dereplicate_wf_operation(**vars(args))
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/controller.py", line 86, in dereplicate_wf_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_workflows.py", line 28, in dereplicate_wrapper
    drep.d_filter.d_filter_wrapper(wd, genomes = genomes, Chdb = Chdb, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 81, in d_filter_wrapper
    Gdb = _get_run_genomeInfo(wd, bdb, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 141, in _get_run_genomeInfo
    Chdb = _run_checkM_wrapper(bdb, workDirectory, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 359, in _run_checkM_wrapper
    run_prodigal(bdb['location'].tolist(), prod_folder, wd=workDirectory, **kwargs)
  File "/Users/kathy/python-virtual-environments/venv/lib/python3.7/site-packages/drep/d_filter.py", line 433, in run_prodigal
    loc = drep.get_exe('prodigal')
AttributeError: module 'drep' has no attribute 'get_exe'

**Comment by MrOlm** [comment]
Hello,

This does seem to be an issue regarding multiple versions of dRep.

I would first uninstall dRep completely, then re-install it and try again. There are two ways of doing this. 1) try "pip uninstall dRep". Hopefully that works. After that, try the command "which dRep". This will tell you where dRep is on your system if it's not completely gone. You can then try and remove dRep from that location manually (using the command rm )

The second option would be to install and start using pyenv (https://github.com/pyenv/pyenv <https://github.com/pyenv/pyenv>). Once pyenv is set up, you would install a new version of python entirely "using the pyenv install" command, and install dRep in that new version of python (pip install dRep).

The first option is easier, but the second option will definitely work.

Once this multiple versions thing is sorted out, I bet the problem with reading completeness and contamination will be sorted out as well.

Best,
Matt

**Comment by jennifer-allott** [comment]
I did try and uninstall dRep completely, then re-install and follow your previous directions re: BarbBranch. Yet now I continue to receive a ModuleNotFound error. The install from GitHub with the BarbBranch feature leads to several nested dRep folders that are more difficult to navigate than the previous install. 

(venv) caelia:drep kathy$ which drep
/Users/kathy/python-virtual-environments/venv/drep/bin//drep
(venv) caelia:drep kathy$ dRep -h
Traceback (most recent call last):
  File "/Users/kathy/python-virtual-environments/venv/drep/bin/dRep", line 26, in <module>
    import drep.argumentParser
ModuleNotFoundError: No module named 'drep'
(venv) caelia:drep kathy$

**Comment by jennifer-allott** [comment]
Unfortunately, that does not solve the issue. I tried uninstalling and reinstalling dRep, and installing dRep anew in a new virtual environment. However, I still get the same error message as above.

**Comment by MrOlm** [comment]
Hello,

From your previous message it looks like you are using venv, which I'm not familiar with. Have you tried using pyenv? (https://github.com/pyenv/pyenv <https://github.com/pyenv/pyenv>). That involves installing a whole new python installation, meaning that all installed modules will definitely start from anew.

Best,
Matt

**Comment by jennifer-allott** [comment]
Hi, perhaps there is another issue? I have used pyenv before, and worked today to reinstall it and try running drep with pyenv again. I receive the same error message as above i.e. 
loc = drep.get_exe('prodigal')
AttributeError: module 'drep' has no attribute 'get_exe' 
Thanks!

**Comment by pulidofabs** [comment]
Hi, 

I am also having the exact same issue as jenniger_allot. I also receive the same error, I am running drep on my hpcc cluster account. I also get the same error stated above.

 loc = drep.get_exe('prodigal')
AttributeError: module 'drep' has no attribute 'get_exe'

**Comment by MrOlm** [comment]
Hello,

It's hard for me to diagnose this problem since it's a problem with how dRep is installed / how Python is setup, not dRep itself, but I can explain what the problem is and suggest a couple of solutions.

`get_exe` is a method with the program `dRep`, specifically in the file `__init__.py`. When dRep is properly installed in python, python should have no problems accessing this method. The fact that python is saying it doesn't dRep doesn't have that attribute means that dRep is not properly installed.

1) Please confirm that you're running an up-to-date version of dRep, and confirm that dRep is installed in the same python environment that is being launched.

2) Consider using `conda` to install and run dRep. conda is a full-service package manager that ensures that programs are properly installed.

Let me know if you have any other questions,
Matt
